remote_theme: pages-themes/tactile@v0.2.0
title: Boxenstopp-Podcast
show_downloads: false

# Podcast settings
podcast:
  title: "Boxenstopp-Podcast"
  author: "Boxenstopp"
  description: >-
    Podcast der Predigten im Boxenstopp

    Boxenstopp ist der Gottesdienst f√ºr Jugendliche und junge Erwachsene der Jungen Kirche Klettgau. Weitere Informationen zum Boxenstopp findest du unter <a href="https://boxenstopp-klettgau.ch">boxenstopp-klettgau.ch</a>.
  language: "ch-de"
  type: "episodic"
  image: "https://podcast.boxenstopp-klettgau.ch/assets/logo.png"
  explicit: false
  guid: "7e99bbfc-6727-51e8-88c4-a7da1440b7ab" # Calculated according to https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md#guid
  categories:
    - text: "Religion &amp; Spirituality"
      subcategory: "Christianity"
  episode_defaults:
    type: "full"
    explicit: false
    image: "logo.png"
    image_url_prefix: "assets"
    audio_type: "audio/mpeg"
    audio_url_prefix: "assets/audio"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
